#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("inspirational.Droid.Resource", IsApplication=true)]

namespace inspirational.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int inspirationalmessageimage1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int inspirationalmessageimage10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int inspirationalmessageimage11 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int inspirationalmessageimage12 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int inspirationalmessageimage13 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int inspirationalmessageimage14 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int inspirationalmessageimage15 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int inspirationalmessageimage16 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int inspirationalmessageimage17 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int inspirationalmessageimage18 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int inspirationalmessageimage19 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int inspirationalmessageimage2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int inspirationalmessageimage20 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int inspirationalmessageimage21 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int inspirationalmessageimage22 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int inspirationalmessageimage23 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int inspirationalmessageimage24 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int inspirationalmessageimage25 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int inspirationalmessageimage26 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int inspirationalmessageimage27 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int inspirationalmessageimage28 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int inspirationalmessageimage29 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int inspirationalmessageimage3 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int inspirationalmessageimage30 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int inspirationalmessageimage31 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int inspirationalmessageimage32 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int inspirationalmessageimage33 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int inspirationalmessageimage34 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int inspirationalmessageimage35 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int inspirationalmessageimage36 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int inspirationalmessageimage37 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int inspirationalmessageimage38 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int inspirationalmessageimage39 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int inspirationalmessageimage4 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int inspirationalmessageimage40 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int inspirationalmessageimage41 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int inspirationalmessageimage42 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int inspirationalmessageimage43 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int inspirationalmessageimage44 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int inspirationalmessageimage45 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int inspirationalmessageimage46 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int inspirationalmessageimage47 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int inspirationalmessageimage48 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int inspirationalmessageimage49 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int inspirationalmessageimage5 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int inspirationalmessageimage50 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int inspirationalmessageimage51 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int inspirationalmessageimage52 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int inspirationalmessageimage53 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int inspirationalmessageimage54 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int inspirationalmessageimage55 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int inspirationalmessageimage56 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int inspirationalmessageimage57 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int inspirationalmessageimage58 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int inspirationalmessageimage59 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int inspirationalmessageimage6 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int inspirationalmessageimage60 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int inspirationalmessageimage61 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int inspirationalmessageimage62 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int inspirationalmessageimage63 = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int inspirationalmessageimage64 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int inspirationalmessageimage65 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int inspirationalmessageimage66 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int inspirationalmessageimage67 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int inspirationalmessageimage68 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int inspirationalmessageimage69 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int inspirationalmessageimage7 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int inspirationalmessageimage70 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int inspirationalmessageimage71 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int inspirationalmessageimage72 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int inspirationalmessageimage73 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int inspirationalmessageimage74 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int inspirationalmessageimage75 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int inspirationalmessageimage76 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int inspirationalmessageimage77 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int inspirationalmessageimage8 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int inspirationalmessageimage9 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int leader1 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int leader10 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int leader11 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int leader12 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int leader13 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int leader14 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int leader15 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int leader2 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int leader3 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int leader4 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int leader5 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int leader6 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int leader7 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int leader8 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int leader9 = 2130837595;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int Link = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int SCROLLER_ID = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int buttonNext = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int buttonPrev = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int imageView1 = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout1 = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int textAuthor = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int textQuote = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int textTitle = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
